import AosModule from "./module/AosModule.js";
// import SwiperModule from "./module/SwiperModule.js";
// import Select2Module from "./module/Select2Module.js";
// import GalleryModule from "./module/GalleryModule.js";
// import TabModule from "./module/TabModule.js";
// import PopupModule from "./module/PopupModule.js";
// import PlusMinusModule from "./module/PlusMinusModule.js";
// import LoadMoreModule from "./module/LoadMoreModule.js";
// import AnimatedModule from "./module/AnimatedModule.js";
// import FilterHandle from "./module/FilterHandle.js";
// import GetFile from "./module/GetFile.js";
// import FixedBar from "./module/FixedBar.js";
// import collapseModule from "./module/collapseModule.js";
// import scrollTitle from "./module/scrollTitle.js";
// import CountUpModule from "./module/CountUpModule.js";
// import ScrollHeader from "./module/ScrollHeader.js";
// import Magnify from "./module/MagnifyModule.js";
// import DatePickerModule from "./module/DatePickerModule.js";
// import addFavo from "./module/addFavo.js";
// import ShowBtnMobile from "./module/ShowBtnMobile.js";
// import RatingModule from "./module/RatingModule.js";
// import AmountModule from "./module/AmountModule.js";
import HamModule from "./module/HamModule.js";


window.addEventListener("DOMContentLoaded", () => {
    AosModule();
    // TabModule();
    // Select2Module();
    // SwiperModule();
    // GalleryModule();
    // PopupModule();
    // PlusMinusModule();
    // LoadMoreModule();
    // AnimatedModule();
    // FilterHandle();
    // GetFile();
    // FixedBar();
    // collapseModule();
    // scrollTitle();
    // CountUpModule();
    // ScrollHeader();
    // Magnify();
    // DatePickerModule();
    // addFavo();
    // ShowBtnMobile();
    // RatingModule();
    // AmountModule();
    HamModule();
});